# docker-compose -f PubSub_Standard_HA_9.4.0.78.YML up -d
version: '3.4'

networks:
  hanet: {}
  
x-environment:
  &default-environment
  username_admin_globalaccesslevel: admin
  username_admin_password: ${ADMIN_PASSWORD:-admin}
  system_scaling_maxconnectioncount: 100
  redundancy_enable: "yes"
  redundancy_group_password: topsecret
  redundancy_group_node_primary_connectvia: primary
  redundancy_group_node_primary_nodetype: message_routing
  redundancy_group_node_backup_connectvia: backup
  redundancy_group_node_backup_nodetype: message_routing
  redundancy_group_node_monitoring_connectvia: monitoring
  redundancy_group_node_monitoring_nodetype: monitoring
  redundancy_authentication_presharedkey_key: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEKMDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEK
  TZ: Asia/Singapore
  umask: 0022
  
x-common:
  &default-common
  image: solace-pubsub-enterprise:${TAG:-9.4.0.78}
  shm_size: 1g
  user: "0"
  ulimits:
    core: 1
    nofile:
      soft: 2448
      hard: 38048
  networks:
    - hanet

services:

  primary:
    container_name: primary
    hostname: primary
    ports:
      - "212:2222"
    volumes:
      - /home/duser/work/certs2:/usr/sw/jail/certs
    environment: 
      << : *default-environment
      routername: primary
      configsync_enable: "yes"
      redundancy_matelink_connectvia: backup
      redundancy_activestandbyrole: primary
      service_semp_tlsport: 1943
    << : *default-common

  backup:
    container_name: backup
    hostname: backup
    ports:
      - "312:2222"
    volumes:
      - /home/duser/work/certs2:/usr/sw/jail/certs
    environment:
      << : *default-environment
      routername: backup
      configsync_enable: "yes"
      redundancy_matelink_connectvia: primary
      redundancy_activestandbyrole: backup
      service_semp_tlsport: 1943
    << : *default-common

  monitoring:
    container_name: monitoring
    hostname: monitoring
    ports:
      - "412:2222"
    volumes:
      - /home/duser/work/certs2:/usr/sw/jail/certs
    environment:
      << : *default-environment
      routername: monitoring
      nodetype: monitoring
      service_semp_tlsport: 1943
    << : *default-common

  lb:
    container_name: lb
    image: 'haproxy:latest'
    volumes:
      - ./assertMaster.perl:/assertMaster.perl
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    entrypoint:
      - /bin/bash
      - "-c"
      - "perl /assertMaster.perl"
    ports:
      - '80:80'
      - '8008:8008'
      - '443:443'
      - '1443:1443'
      - '1943:1943'
      - '1883:1883'
      - '5671:5671'
      - '5672:5672'
      - '8000:8000'
      - '8080:8080'
      - '8443:8443'
      - '8883:8883'
      - '9000:9000'
      - '9001:9001'
      - '9002:9002'
      - '9443:9443'
      - '55555:55555'
      - '55003:55003'
      - '55443:55443'
      - '1936:1936'
      - '9930-9940:9930-9940'
    networks:
      - hanet
